### ISSUE TITLE
I got Errors

### ISSUE THREAD

**Issue by cogdog** [reclaimhosting/site_templates#4]
Sorry, I do not know how to debug these. I tried copying from the aerial template, but messed up.

This is on the new "Eventually" template...

![error](https://user-images.githubusercontent.com/463038/28839048-39b87c3a-76a7-11e7-887b-d9e91f3f7cca.jpg)

**Comment by timmmmyboy** [comment]
Hmmm, ok going to look into this. We may also want to setup a dev branch or something fancy like that we can use and test maybe on stateu.org before pushing out to everyone. Then again I have no problem flying by the seat of my pants :)

**Comment by cogdog** [comment]
That would be "logical" - let's figure out if this is an area we will keep working on, but I am very open to testing cpanel experiments there. Appreciate your taking the time here, I am excited to try out Site Publisher as a First Step in domaining for newbies.

Seat pants flying is all  know ;-)

**Comment by timmmmyboy** [comment]
This was fixed with the latest commit https://github.com/reclaimhosting/site_templates/commit/e6f50b0740e858ca7b7e18663d10798d012944ff
